version: '3.8'

services:
  nextjs-reminder-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - reminder-db:/app/db
    environment:
      - APP_ENV=production

volumes:
  reminder-db:
