version: '3.8'

services:
  nextjs-reminder:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - reminder-db:/app/db
    environment:
      - NODE_ENV=development

volumes:
  reminder-db:
