version: '3.8'

volumes:
  reminder-db:

services:
  nextjs-reminder-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - reminder-db:/usr/src/app/db
    env_file:
      - ./.env
    environment:
      - APP_ENV=production
