version: '3.8'

services:
  nextjs-reminder-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - reminder-db:/app/db
    environment:
      - APP_ENV=development

volumes:
  reminder-db:
